[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
whitelist = "F8JTJRsEngZsdw4HkZDHmDWjJtVXUWCPeSgKFondXVbQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/tony_dev/solana_project/my-wallet3.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
